version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-to-ddb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vy05mkx15lqe"
s3_prefix = "s3-to-ddb"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
